field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  410c9682-a3f7-4475-9013-0453aac4635d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9cb7ea0d-8dd4-4298-ac6c-ab6c0efbe6ba # Snippet Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17c573f3-0377-4ea8-834f-091f04d60568
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: be45c3e2-5e9f-491e-a000-94d95c4fa20b # Snippet
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0187af9-ab3b-48cf-9fa9-8cfb76e48a9e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf5b11e3-a6d6-430f-991f-9b78f9e4dd7f # Snippet collapsed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db3144df-7836-499b-a09c-74aa13fe121c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: c033e8a9-eab3-4bd0-bea5-4a8d2dcf5ad3
        userCondition: null
fields:
  9cb7ea0d-8dd4-4298-ac6c-ab6c0efbe6ba: # Snippet Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: snippetName
    instructions: null
    name: 'Snippet Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  be45c3e2-5e9f-491e-a000-94d95c4fa20b: # Snippet
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: snippet
    instructions: null
    name: Snippet
    searchable: false
    settings:
      availableLanguages:
        - css
        - graphql
        - html
        - javascript
        - json
        - markdown
        - mysql
        - php
        - shell
        - twig
        - typescript
        - yaml
      codeFolding: true
      columnType: text
      defaultValue: ''
      fontSize: 14
      language: javascript
      lineNumbers: true
      monacoEditorOptions: ''
      placeholder: ''
      showLanguageDropdown: true
      singleLineEditor: false
      theme: vs-dark
    translationKeyFormat: null
    translationMethod: none
    type: nystudio107\codefield\fields\Code
  cf5b11e3-a6d6-430f-991f-9b78f9e4dd7f: # Snippet collapsed
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: snippetCollapsed
    instructions: null
    name: 'Snippet collapsed'
    searchable: false
    settings:
      default: false
      offLabel: 'False'
      onLabel: 'True'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: blockCode
name: Code
sortOrder: 13
