field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  6c449cd7-ebc2-4ce6-be61-1e8c90cb176b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 74c3cd4f-b565-4fb4-879e-72022774f93c # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11e9d4b4-edcc-4533-b7a1-8b07c6602017
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 75195ab8-b7c4-4dca-b807-ef8a042ef5a9 # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d10b279e-4bce-49cf-90fd-0a2fae06d537
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62883121-63a2-4e5c-a6f3-4855cf64df2c # Image Ratio
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 721a9d99-a7c1-4462-b772-b18fadab09e8
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e0e9e510-46ff-45aa-aa46-700b325bb911 # Show Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9eae0590-a0dc-4c71-8d19-af63a55af1bd
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 56042e3e-7a7b-4a4c-9222-63e004682c9b
        userCondition: null
fields:
  74c3cd4f-b565-4fb4-879e-72022774f93c: # Variant
    columnSuffix: swaooeeb
    contentColumnType: string(14)
    fieldGroup: null
    handle: variant
    instructions: null
    name: Variant
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - optgroup
              - Grid
        -
          __assoc__:
            -
              - label
              - 'Grid (2 Cols)'
            -
              - value
              - grid2Cols
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Grid (3 Cols)'
            -
              - value
              - grid3Cols
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Grid Calculated'
            -
              - value
              - gridCalculated
            -
              - default
              - ''
        -
          __assoc__:
            -
              - optgroup
              - Gallery
        -
          __assoc__:
            -
              - label
              - Gallery
            -
              - value
              - gallery
            -
              - default
              - ''
        -
          __assoc__:
            -
              - optgroup
              - Slider
        -
          __assoc__:
            -
              - label
              - Slider
            -
              - value
              - slider
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  75195ab8-b7c4-4dca-b807-ef8a042ef5a9: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:6c5fc0dd-cf56-48d8-8af8-88abe763b970' # Files
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      targetSiteId: null
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  62883121-63a2-4e5c-a6f3-4855cf64df2c: # Image Ratio
    columnSuffix: null
    contentColumnType: string(16)
    fieldGroup: null
    handle: imageRatio
    instructions: 'Usable for: Grids (non calculated) / Sliders'
    name: 'Image Ratio'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Landscape
            -
              - value
              - aspect-landscape
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - aspect-square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - aspect-portrait
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Auto
            -
              - value
              - aspect-auto
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  e0e9e510-46ff-45aa-aa46-700b325bb911: # Show Image Caption
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showImageCaption
    instructions: 'Usable for: Grids'
    name: 'Show Image Caption'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: blockImages
name: Images
sortOrder: 6
