field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  12757233-a8be-4796-bed0-bdaffeb488ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d4cabad1-1cae-4a1e-a914-c38d9f1a813a # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b98c8af-6fb9-4a18-b577-3f75b079e8f2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f371c36b-db60-4c3f-a1dc-a3e11244e2ca
        userCondition: null
fields:
  d4cabad1-1cae-4a1e-a914-c38d9f1a813a: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      ckeConfig: 6f4a3e01-23de-4313-8109-00a430317d11 # Rich Text Default
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: true
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: blockText
name: Text
sortOrder: 2
