field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  58ddc97d-9694-4104-a136-b6344987e1b6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 35b67fb3-4bdb-470f-a686-3d46c5cd5f96 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cd02812-349c-46d5-a4b7-57700a221566
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9b73b533-898f-4f77-a500-37ea0be0afc7 # Show Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 089ab2ac-9335-40c2-9827-f4dd1baca5dc
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 70bc887b-faf2-45c7-b4bc-4299acd343da # Image Ratio
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0fb63ad-8f84-4caf-a7b6-c0e44deeae12
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1be86da8-5273-40c6-ba88-718f5c32a6c3 # Image Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 744a7c6f-6d25-4c12-8d70-9a8752b5f5f6
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 5e8a312e-45d0-491c-924d-84d96af3b270
        userCondition: null
fields:
  1be86da8-5273-40c6-ba88-718f5c32a6c3: # Image Width
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageWidth
    instructions: null
    name: 'Image Width'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Wide
            -
              - value
              - wide
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Narrow
            -
              - value
              - narrow
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  9b73b533-898f-4f77-a500-37ea0be0afc7: # Show Image Caption
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showImageCaption
    instructions: null
    name: 'Show Image Caption'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  35b67fb3-4bdb-470f-a686-3d46c5cd5f96: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:6c5fc0dd-cf56-48d8-8af8-88abe763b970' # Files
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      sources:
        - 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      targetSiteId: null
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  70bc887b-faf2-45c7-b4bc-4299acd343da: # Image Ratio
    columnSuffix: null
    contentColumnType: string(16)
    fieldGroup: null
    handle: imageRatio
    instructions: null
    name: 'Image Ratio'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Landscape
            -
              - value
              - aspect-landscape
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - aspect-square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - aspect-portrait
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Auto
            -
              - value
              - aspect-auto
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: blockImage
name: Image
sortOrder: 5
