color: null
fieldLayouts:
  4423c5be-938a-4871-bd99-52e14a8de079:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: f084e099-613d-4405-b600-f4be12d3509b
            handle: null
            includeInCards: true
            instructions: null
            label: 'Divider Variant'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b37c0cae-90a6-44b1-95f1-c0fbb5c25213
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ae8f94aa-5f01-405e-9c05-1294f1d44a6a
        userCondition: null
handle: blockDivider
hasTitleField: false
icon: null
name: Divider
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
