color: null
fieldLayouts:
  1abefa28-ba0b-4e7e-be2b-12835562bb01:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 63bd200d-3882-4788-a8ba-528452521d6c
            handle: null
            includeInCards: true
            instructions: null
            label: 'Video Provider'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61617279-3f13-4142-9007-28c5defd3157
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: e9486b85-fd5e-40c8-851b-a6b0133e1f88
            handle: null
            includeInCards: false
            instructions: null
            label: 'Video Id'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 209e0b27-694f-492c-8618-f97820ac8a2a
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 3ac3bfdf-e50b-46e3-abb9-cef4bffab4a0
            handle: null
            includeInCards: false
            instructions: null
            label: Autoplay
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85e4faf3-8c53-4926-9624-5ba7b9cca49b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 4a25e574-679a-4d01-8e8b-d5927129ce33
            handle: null
            includeInCards: false
            instructions: null
            label: Loop
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca8a500e-d6df-4d29-b957-9e9f7172facc
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 68109da0-245f-4b21-b040-b7f4385e618e
            handle: null
            includeInCards: false
            instructions: null
            label: 'Video Width'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b9c294a-c00e-4b45-b0e5-c0ff793155ac
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: bb2df4f8-8532-459f-ae5f-12b9013d58c0
        userCondition: null
handle: blockVideo
hasTitleField: false
icon: null
name: Video
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
