color: null
fieldLayouts:
  410c9682-a3f7-4475-9013-0453aac4635d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 9cb7ea0d-8dd4-4298-ac6c-ab6c0efbe6ba
            handle: null
            includeInCards: true
            instructions: null
            label: 'Snippet Name'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17c573f3-0377-4ea8-834f-091f04d60568
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: be45c3e2-5e9f-491e-a000-94d95c4fa20b
            handle: null
            includeInCards: false
            instructions: null
            label: Snippet
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0187af9-ab3b-48cf-9fa9-8cfb76e48a9e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: cf5b11e3-a6d6-430f-991f-9b78f9e4dd7f
            handle: null
            includeInCards: false
            instructions: null
            label: 'Snippet collapsed'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db3144df-7836-499b-a09c-74aa13fe121c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: c033e8a9-eab3-4bd0-bea5-4a8d2dcf5ad3
        userCondition: null
handle: blockCode
hasTitleField: false
icon: null
name: Code
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
