color: null
fieldLayouts:
  12757233-a8be-4796-bed0-bdaffeb488ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: d4cabad1-1cae-4a1e-a914-c38d9f1a813a
            handle: null
            includeInCards: true
            instructions: null
            label: Text
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b98c8af-6fb9-4a18-b577-3f75b079e8f2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f371c36b-db60-4c3f-a1dc-a3e11244e2ca
        userCondition: null
handle: blockText
hasTitleField: false
icon: null
name: Text
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
