color: null
fieldLayouts:
  a4335b2d-af34-4544-b20a-e4a928a3693c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: 1b37c439-5a32-4e8f-8019-7f6a94593419
            handle: null
            includeInCards: true
            instructions: null
            label: 'Spacer Variant'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8ba7044-fa9a-4546-9493-16bccb73a76e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1ce6448e-436d-4f3c-b18e-d4b338f00b99
        userCondition: null
handle: blockSpacer
hasTitleField: false
icon: null
name: Spacer
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
