color: red
fieldLayouts:
  d9e47404-d530-49be-957f-79a2ee567d15:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T19:47:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0024100c-6131-4b31-a1cd-50ee6822faee
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T21:49:33+00:00'
            elementCondition: null
            fieldUid: edfcb398-ef78-43ec-9434-d6405da2886e # Text Single
            handle: customTitle
            includeInCards: true
            instructions: null
            label: 'Custom Title'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abdec6db-b69b-4442-a975-f3914939eed0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T21:49:33+00:00'
            elementCondition: null
            fieldUid: 5af0a821-fa33-490a-9439-3193f439dd06 # Rich Text Simple
            handle: description
            includeInCards: true
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52a340af-509e-4a53-a463-4b9979951c92
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T21:49:33+00:00'
            elementCondition: null
            fieldUid: b81cb731-dd6f-4055-9c6d-2f076a727a27 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f8401b2-798f-4371-b0c0-4319dcaa9e6e
            userCondition: null
            warning: null
            width: 100
        name: Entry
        uid: 8ccd4ebc-87b4-4708-9e42-be5f4a588429
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T21:49:33+00:00'
            elementCondition: null
            fieldUid: 75f91f6f-fc53-49ad-bde0-365d6384b711 # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59d3d0c6-9239-4811-be11-feddc828af1a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5052bf85-c159-48ca-8026-63ffdc7fea05
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            fieldUid: d29e8520-ab62-4c8f-bda2-61868797c1ca # SEOmatic
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de3b8d47-3711-4e69-a7d6-d9828792176f
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 1f04ebd9-d50b-4ebb-b0a1-3e175abc5c8b
        userCondition: null
handle: entryNewsDetail
hasTitleField: true
icon: memo
name: '_News Detail'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
