fieldLayouts:
  39b9e1a8-a9fe-46a4-aad9-966389ae8743:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dd63bc42-f4e0-4ecd-a5c7-288a5e7946b2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1516a801-6243-468d-b8e2-479085458faa # Text: Title Overwrite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7871ee59-389b-4aea-a495-9f9760c83be4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 45510f13-91d2-479f-9ff2-68dd09ab6643 # Text: Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e249e650-b151-4cd9-aabb-a505665947c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0dc851b0-a289-4c50-be8d-0c055b270ee8 # Asset: Entry Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd27b23d-962d-4454-a2ad-8d680b53033c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 19f2f3ee-8dd2-4cb7-a283-067d9468d7a5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d29e8520-ab62-4c8f-bda2-61868797c1ca # SEO: SEOmatic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee0f87a2-09fe-40be-ae32-32d65f24fb3f
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 19225308-28cc-46b1-8075-f4dc542c6c81
        userCondition: null
handle: pageNews
hasTitleField: true
name: 'Page News'
section: b0207f48-be48-49ab-a759-1ff51f232df3 # Pages
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
