defaultPlacement: end
fieldLayouts:
  abc08fce-9bc1-47bb-bd1e-278fb69164f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T19:47:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 81c1e3d1-2c86-4c02-a36b-c9df669614b0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-04T19:47:47+00:00'
            elementCondition: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: cd7c26f1-2929-4d18-9390-01ccaadf71ac
            userCondition: null
            warning: null
        name: Content
        uid: 17345704-8e0e-4a2f-8e32-a06e66b18860
        userCondition: null
handle: navigationMain
instructions: null
maxNodes: null
name: 'Navigation Main'
permissions:
  craft\elements\Asset:
    enabled: ''
    permissions: '*'
  craft\elements\Category:
    enabled: ''
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  8153a2df-373f-4aac-9a92-d52292c9f1aa: # Baukasten
    enabled: true
sortOrder: 1
structure:
  maxLevels: 3
  uid: 0ba622b0-32db-4ff9-b9e9-46ae3f392176
