fieldLayouts:
  0a4045e3-76db-4cd4-8347-e2eab25d0bd1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 08838209-78ab-4068-a8e0-044ff96432ee
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1516a801-6243-468d-b8e2-479085458faa # Text: Title Overwrite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c0fd1ef-397e-44f0-8712-e185c9f4d918
            userCondition: null
            warning: null
            width: 50
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: f72b83ba-aa44-462e-8c1c-f8c5745b35ac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aac37142-e533-49aa-8665-b8cc6360e98b # Text: Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc9d4562-974b-4af0-b234-d24d1162cdfa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 419ebfbb-8723-48db-ae89-10adf52cdf11 # Text: Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6dd6ce4-f0ce-4c5f-99fe-c1bf7d423b60
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8780cb03-c9ea-4482-ab85-3e541453b50f # Text: Source Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 965a2160-44cc-416d-a8dd-b648efa3ca13
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 17490b94-d86a-40c5-bc48-932d8c81319f
        userCondition: null
fs: images
handle: images
name: Images
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: craft-transforms/images
