fieldLayouts:
  38d718c0-a8fd-4a1e-8136-9daf72525bd7:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5564ba9c-342c-4e49-9683-d969feeeb42a
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 075f5d0e-9a65-41f1-8c51-7ed3adf3af4a
            warning: null
            width: 100
          -
            fieldUid: 1516a801-6243-468d-b8e2-479085458faa # Asset: Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0bd6183-760a-4b3a-a0dc-890d9372af0c
            warning: null
            width: 100
          -
            fieldUid: aac37142-e533-49aa-8665-b8cc6360e98b # Asset: Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e12b584-9c3e-4c85-8577-6ca6ca65f5f6
            warning: null
            width: 100
          -
            fieldUid: 419ebfbb-8723-48db-ae89-10adf52cdf11 # Asset: Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a8109f1-1145-4234-bf4d-4506458a7b50
            warning: null
            width: 100
          -
            fieldUid: 8780cb03-c9ea-4482-ab85-3e541453b50f # Asset: Source Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfa095c2-b25d-4775-b3c6-cd2b72777b21
            warning: null
            width: 100
        name: Content
        uid: a335ade1-e2fd-4066-8c0c-764bb223afa4
fs: templateImages
handle: templateImages
name: 'Template Images'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: craft-transforms/templateImages
