fieldLayouts:
  1c050c97-46a7-44da-8b07-841009d282f4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0d54794f-2cbf-4dce-9dd1-0375444002b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 485f0e1d-ef6b-4035-8a72-8fc0c4ca553a # Asset: Alt Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75829680-c619-4cec-a5d5-518fb51a02cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1516a801-6243-468d-b8e2-479085458faa # Asset: Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9ac3637-99ff-4db2-8b7a-79c4415f181c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aac37142-e533-49aa-8665-b8cc6360e98b # Asset: Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3cc5b53e-0cd2-49da-8c61-cc39d3cbb1c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 419ebfbb-8723-48db-ae89-10adf52cdf11 # Asset: Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0324cf8-4bb0-4eae-ae10-820e7fbb69a2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8780cb03-c9ea-4482-ab85-3e541453b50f # Asset: Source Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ceafbea2-4ca5-409e-91b4-8b1bfbbae6ea
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7fa2cead-3f59-4c5b-8562-8ee83d4acf7b
        userCondition: null
fs: users
handle: users
name: Users
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: transforms
transformSubpath: craft-transforms/users
