columnSuffix: ibratpfs
contentColumnType: text
fieldGroup: d6a382fb-fadf-4449-8e74-b89f2c649c4c # Entry
handle: entrySeo
instructions: ''
name: 'Entry: SEO'
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoPreview
    - mainEntityOfPage
    - seoTitle
    - seoDescription
    - seoKeywords
    - seoImage
    - robots
    - canonicalUrl
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
