columnSuffix: tfqyxyzy
contentColumnType: string(560)
fieldGroup: d6a382fb-fadf-4449-8e74-b89f2c649c4c # Entry
handle: entryShortDescription
instructions: ''
name: 'Entry: Short Description'
searchable: true
settings:
  byteLimit: null
  charLimit: 140
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
