columnSuffix: null
handle: images
instructions: null
name: Images
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:6c5fc0dd-cf56-48d8-8af8-88abe763b970' # Files
  restrictedLocationSubpath: null
  selectionLabel: 'Add images'
  showCardsInGrid: false
  showSiteMenu: true
  showUnpermittedFiles: true
  showUnpermittedVolumes: true
  sources:
    - 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
  targetSiteId: null
  validateRelatedElements: true
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
