columnSuffix: null
handle: imageRatio3
instructions: null
name: 'Builder: Content - Image - Image Ratio'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Landscape
        -
          - value
          - aspect-landscape
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - aspect-square
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Portrait
        -
          - value
          - aspect-portrait
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Auto
        -
          - value
          - aspect-auto
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
