columnSuffix: null
handle: richTextSimple
instructions: null
name: 'Rich Text Simple'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: e8b10d27-be46-4108-9bf5-3a8711280165 # Rich Text Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
