columnSuffix: null
handle: richText
instructions: null
name: 'Rich Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 6f4a3e01-23de-4313-8109-00a430317d11 # Rich Text
  createButtonLabel: Blocks
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
