columnSuffix: null
handle: sectionPaddingVertical
instructions: null
name: 'Builder: Content - Section - Section Padding Vertical'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Zero
        -
          - value
          - zero
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - SM
        -
          - value
          - sm
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - MD
        -
          - value
          - md
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - LG
        -
          - value
          - lg
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - XL
        -
          - value
          - xl
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 2XL
        -
          - value
          - 2xl
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
