columnSuffix: null
handle: sourceUrl
instructions: null
name: 'Builder: Content - Quote - Source Url'
searchable: false
settings:
  maxLength: 255
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
