columnSuffix: msfzxjxb
handle: videoProvider
instructions: null
name: 'Builder: Content - Video - Video Provider'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Youtube
        -
          - value
          - youtube
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Vimeo
        -
          - value
          - vimeo
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
