dateModified: 1670447494
elementSources:
  craft\elements\Asset:
    -
      key: 'volume:6c5fc0dd-cf56-48d8-8af8-88abe763b970' # Files
      type: native
    -
      disabled: false
      key: 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
        - imageSize
      type: native
    -
      disabled: false
      key: 'volume:77c74b5c-6bbb-41a7-b166-c6b158a3cc7f' # Template Images
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
        - imageSize
      type: native
    -
      key: 'volume:8dda1580-81a2-49f5-9dd2-ed1e2eb03fc6' # Users
      type: native
    -
      key: 'folder:c8e15363-b103-4fd2-b6e4-097752fa2cef'
      type: native
email:
  fromEmail: $SYSTEM_MAIL
  fromName: $SITE_NAME
  replyToEmail: $REPLY_MAIL
  template: null
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
fs:
  files:
    hasUrls: true
    name: Files
    settings:
      path: '@webroot/assets/files'
    type: craft\fs\Local
    url: '@assetsUrl/files/'
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/assets/images'
    type: craft\fs\Local
    url: '@assetsUrl/images/'
  templateImages:
    hasUrls: true
    name: 'Template Images'
    settings:
      path: '@webroot/assets/templateImages'
    type: craft\fs\Local
    url: '@assetsUrl/templateImages/'
  transforms:
    hasUrls: true
    name: Transforms
    settings:
      path: '@webroot/assets/transforms'
    type: craft\fs\Local
    url: '@assetsUrl/transforms/'
  users:
    hasUrls: true
    name: Users
    settings:
      path: '@webroot/assets/users'
    type: craft\fs\Local
    url: '@assetsUrl/users/'
meta:
  __names__:
    0a7dd988-f4db-40b7-8112-6f6fc7c4fb54: Text # Text
    0a686d89-8754-4f00-a79e-fed75548909d: Images # Images
    0dc851b0-a289-4c50-be8d-0c055b270ee8: 'Entry: Image' # Entry: Image
    1a64748f-2870-4c18-a869-f2b050ede5ba: 'Image Transform' # Image Transform
    1b37c439-5a32-4e8f-8019-7f6a94593419: 'Spacer Variant' # Spacer Variant
    1be86da8-5273-40c6-ba88-718f5c32a6c3: 'Image Width' # Image Width
    1c94bbf7-46b0-46e4-a699-b4eef42994a0: 'Text Basic' # Text Basic
    2bc1feee-cfc8-48ee-bace-f101e7f41ac9: Default # Default
    2c12b530-3423-45aa-a4ad-92cd9da42fd0: 'Single Fields' # Single Fields
    2f642060-4792-41cb-a427-083aabeba231: 'Content Builder' # Content Builder
    3ac3bfdf-e50b-46e3-abb9-cef4bffab4a0: Autoplay # Autoplay
    4a25e574-679a-4d01-8e8b-d5927129ce33: Loop # Loop
    5c9f2ce6-f780-4ea6-a50c-539a252aec94: 'Image Grid' # Image Grid
    5d0f7961-203c-4008-a55a-6a7d35e7a37a: Home # Home
    6a90dae3-938c-47e6-8e36-6b1d6be92d63: 'Show Image Caption' # Show Image Caption
    6b6fa06a-49a5-4d76-86c2-73025061e123: 'Image Columns' # Image Columns
    6c5fc0dd-cf56-48d8-8af8-88abe763b970: Files # Files
    6d94dcc4-6ec1-45b4-8c86-e53cee842b11: 'Overview News' # Overview News
    7b3b13e0-e20d-4d51-b0ae-832300f45234: Text # Text
    7b23a4a8-a6f8-43c4-b12c-326d089176ad: 'Video Youtube' # Video Youtube
    7e8fd607-0b56-4196-9e02-76ebba9ad7bd: New # New
    7eb1a718-0679-4fda-b656-9bfdf55a2025: 'Navigation Main' # Navigation Main
    8ced5be5-13b2-483f-8db9-aab9757aad21: Error # Error
    8dda1580-81a2-49f5-9dd2-ed1e2eb03fc6: Users # Users
    9a8fffce-3c28-4326-8f7a-e31d2f6cc04b: 'Section Background Color' # Section Background Color
    9b0f2718-07f3-4577-9fec-20385cba4c33: 'Image Slider' # Image Slider
    9b73b533-898f-4f77-a500-37ea0be0afc7: 'Show Image Caption' # Show Image Caption
    9cb7ea0d-8dd4-4298-ac6c-ab6c0efbe6ba: 'Snippet Name' # Snippet Name
    35b67fb3-4bdb-470f-a686-3d46c5cd5f96: Image # Image
    53f0660a-f06b-4b2d-b342-1869c5c65538: Quote # Quote
    55a8f195-17f6-41b9-983f-06bb0d4b973e: 'Entry: Custom Title' # Entry: Custom Title
    63e3914d-ee70-44c2-9dc3-91551f47c54f: 'Text Advanced' # Text Advanced
    70bc887b-faf2-45c7-b4bc-4299acd343da: 'Image Transform' # Image Transform
    74b87138-1475-47c2-a9dd-63baa78dd5f5: 'Space Between Blocks' # Space Between Blocks
    74eb36ae-7a26-4e7d-b454-990ec52617f0: 'Builder: Content' # Builder: Content
    75b6f580-613f-42ae-aa23-2d5fb22ff3da: 'Source Subline' # Source Subline
    77c74b5c-6bbb-41a7-b166-c6b158a3cc7f: 'Template Images' # Template Images
    81d0ea50-f7e1-4eff-8138-2a06ffbfae86: Home # Home
    88f5b6a1-8725-4770-b8df-f5f3c0d257d3: 'Section Width' # Section Width
    98f7a455-6764-4b7d-8d19-405bdcc42228: 'Image Transform' # Image Transform
    210de09a-f6c8-42dd-b4d6-c1c00e7d0b82: 'Image Position' # Image Position
    359d175b-2fe0-421b-959a-16ca87c71044: Contact # Contact
    419ebfbb-8723-48db-ae89-10adf52cdf11: 'Asset: Source' # Asset: Source
    485f0e1d-ef6b-4035-8a72-8fc0c4ca553a: 'Asset: Alt Text' # Asset: Alt Text
    1509cbec-547c-4338-bcc8-a5452ab8c801: Images # Images
    1516a801-6243-468d-b8e2-479085458faa: 'Asset: Title' # Asset: Title
    3497ad65-5e4c-43cb-b469-c3e4b3d80343: 'Text : Floating Image' # Text : Floating Image
    3547e7b4-f3fb-4cf4-9d29-9f12dfa94594: News # News
    8153a2df-373f-4aac-9a92-d52292c9f1aa: Baukasten # Baukasten
    8512e79b-4bb8-4d2d-b731-5fa98546f2c9: Builders # Builders
    8780cb03-c9ea-4482-ab85-3e541453b50f: 'Asset: Source Url' # Asset: Source Url
    9005a655-4d9f-46b4-8c33-aadba34b6112: 'Social Sharing Facebook' # Social Sharing Facebook
    45510f13-91d2-479f-9ff2-68dd09ab6643: 'Entry: Short Description' # Entry: Short Description
    68109da0-245f-4b21-b040-b7f4385e618e: 'Video Width' # Video Width
    75195ab8-b7c4-4dca-b807-ef8a042ef5a9: Images # Images
    89272b00-6f81-47f7-9335-4367edcac941: Images # Images
    92963d20-e763-4d2e-a367-9e543dfde522: Spacer # Spacer
    231200a9-ef7d-4002-8155-54fcaf4f6e6c: 'Image Width' # Image Width
    295738c1-951d-4b8c-b5cd-83d71a85d7e8: Image # Image
    0528527a-c400-4aeb-8d16-b5fea2a082f6: 'Show Image Caption' # Show Image Caption
    644167c0-ab2a-4f9d-9b2b-09f5a6556ef3: 'Public Schema' # Public Schema
    62883121-63a2-4e5c-a6f3-4855cf64df2c: 'Image Transform' # Image Transform
    a2484323-15c1-4358-a188-d18a600c5958: Autoplay # Autoplay
    aa7883a4-2cce-4316-85f3-ec6ea59402ec: 'Section Padding Vertical' # Section Padding Vertical
    aac37142-e533-49aa-8665-b8cc6360e98b: 'Asset: Caption' # Asset: Caption
    b0207f48-be48-49ab-a759-1ff51f232df3: Pages # Pages
    b3a90095-2af8-4c53-a0dd-6e7d9f80d628: 'Image Gallery' # Image Gallery
    b81cb731-dd6f-4055-9c6d-2f076a727a27: Image # Image
    b3022ef5-7f1b-49d7-976d-5d5be501c1f1: Section # Section
    b48826ad-7083-4a54-8082-52ede1c340b7: 'Video ID' # Video ID
    be45c3e2-5e9f-491e-a000-94d95c4fa20b: Snippet # Snippet
    c6d6d63e-16f8-4450-a631-a9d6a37d2d88: 'Video Width' # Video Width
    c40b8b5e-0ccb-4d0d-9eee-bd24ac9209b0: Source # Source
    cf5b11e3-a6d6-430f-991f-9b78f9e4dd7f: 'Snippet collapsed' # Snippet collapsed
    d4cabad1-1cae-4a1e-a914-c38d9f1a813a: Text # Text
    d6a382fb-fadf-4449-8e74-b89f2c649c4c: Entry # Entry
    d29e8520-ab62-4c8f-bda2-61868797c1ca: 'Entry: SEO' # Entry: SEO
    d383bdc6-fcfa-4652-9155-d7ead2d89f29: Assets # Assets
    df1d53fb-d9ed-4066-93e5-a46aac3f458e: 'Image Columns' # Image Columns
    e0e9e510-46ff-45aa-aa46-700b325bb911: 'Show Image Caption' # Show Image Caption
    e3c7bdf5-9e45-4977-ba11-1e2c4b57644e: Divider # Divider
    e11e03f7-19c1-45c3-935e-1994a7ce7d26: 'Source Url' # Source Url
    e5172a18-ed16-4229-89ca-fc0dc776597a: 'Error Pages' # Error Pages
    e6857cd6-fc09-4396-93bd-3a9fc9011446: 'Snippet Language' # Snippet Language
    e9486b85-fd5e-40c8-851b-a6b0133e1f88: 'Video Id' # Video Id
    e55876f6-9fe1-448f-b0bb-320990caabee: Loop # Loop
    edce675c-a7e5-40e3-bff5-8ec2f77a08cd: 'Image Grid Calculated' # Image Grid Calculated
    f084e099-613d-4405-b600-f4be12d3509b: 'Divider Variant' # Divider Variant
    f1b38495-8096-48fa-9b78-0da345e3295c: Images # Images
    f3e1a215-a60f-4d6a-8897-e1a80a40c6cd: Code # Code
    f4959e03-fec0-4b1c-887e-5301a5f66742: 'Social Sharing Twitter' # Social Sharing Twitter
    fa02ff5a-1741-4417-8c8f-b72b954dd4fd: Quote # Quote
    fb701216-3e80-4e6d-99d4-2e5f70561e22: 'Content Builder' # Content Builder
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_BLITZ
    schemaVersion: 4.2.0
    settings:
      integrations:
        - putyourlightson\blitz\drivers\integrations\CommerceIntegration
  cp-clearcache:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: ''
      cssFile: /dist/css/controlPanelCss.css
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  elements-panel:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_FORMIE
    schemaVersion: 2.0.10
    settings:
      ajaxTimeout: 10
      captchas:
        __assoc__:
          -
            - recaptcha
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Recaptcha
                -
                  - enabled
                  - false
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - recaptcha
                      -
                        - secretKey
                        - ''
                      -
                        - siteKey
                        - ''
                      -
                        - type
                        - v3
                      -
                        - size
                        - normal
                      -
                        - theme
                        - light
                      -
                        - badge
                        - bottomright
                      -
                        - language
                        - en
                      -
                        - minScore
                        - '0.5'
          -
            - duplicate
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Duplicate
                -
                  - enabled
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - duplicate
          -
            - honeypot
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Honeypot
                -
                  - enabled
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - honeypot
          -
            - javascript
            -
              __assoc__:
                -
                  - type
                  - verbb\formie\integrations\captchas\Javascript
                -
                  - enabled
                  - true
                -
                  - settings
                  -
                    __assoc__:
                      -
                        - handle
                        - javascript
                      -
                        - minTime
                        - '10'
      defaultDateDisplayType: ''
      defaultDateTime: ''
      defaultDateValueOption: ''
      defaultEmailTemplate: ''
      defaultFileUploadVolume: ''
      defaultFormTemplate: ''
      defaultInstructionsPosition: below-input
      defaultLabelPosition: above-input
      defaultPage: forms
      enableCsrfValidationForGuests: true
      enableGatsbyCompatibility: false
      enableUnloadWarning: true
      maxIncompleteSubmissionAge: 30
      maxSentNotificationsAge: 30
      pluginName: Formie
      saveSpam: true
      sendEmailAlerts: false
      sentNotifications: true
      spamBehaviour: showSuccess
      spamBehaviourMessage: ''
      spamEmailNotifications: false
      spamKeywords: ''
      spamLimit: 1000
      useQueueForIntegrations: true
      useQueueForNotifications: true
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  imager-x:
    edition: pro
    enabled: true
    licenseKey: $PLUGIN_IMAGERX
    schemaVersion: 4.0.0
  matrixmate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_NAVIGATION
    schemaVersion: 2.0.7
  palette:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  quick-field:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_SEOMATIC
    schemaVersion: 3.0.11
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: local
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: '1'
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 'null'
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: '1'
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: '1'
      truncateTitleTags: '1'
  sherlock:
    edition: lite
    enabled: true
    schemaVersion: 4.1.0
    settings:
      strictTransportSecurity:
        canFail: true
        threshold: 15552000
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: Baukasten
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: '{username}'
  photoVolumeUid: 6c5fc0dd-cf56-48d8-8af8-88abe763b970 # Files
  requireEmailVerification: true
