dateModified: 1617956181
email:
  fromEmail: $SYSTEM_MAIL
  fromName: $SITE_NAME
  replyToEmail: $REPLY_MAIL
  template: ''
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  blitz-recommendations:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  code-mirror:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-clearcache:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: ''
      cssFile: /controlPanelCss.css
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  elements-panel:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  empty-coalesce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.3.0
  formie:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_FORMIE
    schemaVersion: 1.1.7
  imager-x:
    edition: pro
    enabled: true
    licenseKey: $PLUGIN_IMAGERX
    schemaVersion: 3.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: 6ZMS6ZV0QCU2B3CUZFFK37XR
    schemaVersion: 1.0.21
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  retour:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_RETOUR
    schemaVersion: 3.0.9
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 04LFTP58RBAPLNIE9JJQHIDT
    schemaVersion: 3.0.9
  sprout-encode-email:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  string-base64:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  twig-perversion:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  twig-profiler:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  webperf:
    edition: standard
    enabled: true
    licenseKey: $PLUGIN_WEBPERF
    schemaVersion: 1.0.1
    settings:
      automaticallyTrimDataSamples: true
      automaticallyTrimErrorSamples: true
      connectThreshold: 0.5
      craftDbMsThreshold: !!float 2
      craftOtherMsThreshold: !!float 2
      craftTotalMsThreshold: !!float 2
      craftTwigMsThreshold: !!float 2
      dashboardAverageColor: '#ffff00'
      dashboardFastColor: '#00c800'
      dashboardSlowColor: '#c80000'
      dataSamplesStoredLimit: 100000
      displaySidebar: true
      dnsThreshold: 0.5
      domInteractiveThreshold: !!float 5
      errorSamplesStoredLimit: 1000
      excludePatterns:
        -
          __assoc__:
            -
              - pattern
              - '/webperf/.*'
        -
          __assoc__:
            -
              - pattern
              - '/cpresources/.*'
        -
          __assoc__:
            -
              - pattern
              - '/retour/.*'
        -
          __assoc__:
            -
              - pattern
              - '/seomatic/.*'
      filterBotUserAgents: true
      firstByteThreshold: !!float 2
      firstContentfulPaintThreshold: !!float 5
      firstPaintThreshold: !!float 5
      includeBeacon: true
      includeCraftProfiling: true
      includeCraftWarnings: true
      pageLoadThreshold: !!float 10
      pluginName: Webperf
      rateLimitMs: 500
      samplesRateLimitMs: '3600000'
      staticCachedSite: false
      trimOutlierDataSamples: true
      webpageTestApiKey: ''
system:
  edition: pro
  live: true
  name: $SITE_NAME
  schemaVersion: 3.6.7
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  defaultGroup: ''
  photoSubpath: '{username}'
  photoVolumeUid: 428c6546-4871-45b9-9fe9-00512b88c4d2
  requireEmailVerification: true
  suspendByDefault: false
