defaultPlacement: end
enableVersioning: false
entryTypes:
  - 8ced5be5-13b2-483f-8db9-aab9757aad21 # _Error
handle: errorPages
maxAuthors: 1
name: 'Error Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8153a2df-373f-4aac-9a92-d52292c9f1aa: # Baukasten
    enabledByDefault: true
    hasUrls: true
    template: entryTypes/_routerViews.twig
    uriFormat: 'error/{slug}'
type: channel
