defaultPlacement: end
enableVersioning: true
entryTypes:
  - 81d0ea50-f7e1-4eff-8138-2a06ffbfae86 # _Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  8153a2df-373f-4aac-9a92-d52292c9f1aa: # Baukasten
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
