defaultPlacement: end
enableVersioning: true
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8153a2df-373f-4aac-9a92-d52292c9f1aa: # Baukasten
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
