defaultPlacement: end
enableVersioning: true
entryTypes:
  - 2f642060-4792-41cb-a427-083aabeba231 # _Content Builder
  - 6d94dcc4-6ec1-45b4-8c86-e53cee842b11 # _List: News
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  8153a2df-373f-4aac-9a92-d52292c9f1aa: # Baukasten
    enabledByDefault: true
    hasUrls: true
    template: entryTypes/_routerViews.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: 3
  uid: f690c366-ca7d-46e4-89ba-e332e9f3a92b
type: structure
